<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataBoss.Data\DataBoss.Data.csproj" />
    <ProjectReference Include="..\DataBoss.Linq\DataBoss.Linq.csproj" />
  </ItemGroup>

</Project>
